---
language: node_js
node_js:
<<<<<<< HEAD
  - "4"
=======
  - "0.12"
>>>>>>> 9005eb36c5b4b06c8450f944f142fbf2c105ab6d

sudo: false

cache:
  directories:
    - node_modules

before_install:
<<<<<<< HEAD
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - phantomjs --version

install:
=======
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
>>>>>>> 9005eb36c5b4b06c8450f944f142fbf2c105ab6d
  - npm install
  - bower install

script:
  - npm test
